CREATE TYPE "level_status" AS ENUM (
  'beginner',
  'intermediate',
  'advanced'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "edad" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "teacher" varchar NOT NULL,
  "level" level_status,
  "user_id" int
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL,
  "course_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "course_id" int
);

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("id") REFERENCES "courses" ("id");



insert into users (
	name,
	email,
	"password",
	edad
) values (
	'Esteban',
	'daes021@hotmail.com',
	'123456789',
	29
) , (
	'Juan',
	'juanjo01@hotmail.com',
	'987654321',
	3
);

select * from courses;
select * from users;
select * from course_video;
select * from categories;
	
insert into courses (
	title,
	description,
	teacher,
	level,
	user_id 
) values (
	'Fundamentos de Desarrollo Web',
	'Lorem Ipsum',
	'Brayan Munoz',
	'beginner',
	1
) , (
	'Desarrollo de Aplicaciones Web con React',
	'Lorem Ipsum',
	'Junior Pacheco',
	'intermediate',
	2
);

insert into course_video (
	title,
	url,
	course_id
) values (
	'Introducción al Diseño y Desarrollo Web',
	'https://youtu.be/m86Bdh47IZM',
	1	
) , (
	'¿Que es Reac y como funciona?',
	'https://youtu.be/lWQ69WX7-hA',
	2
);

insert into categories (
	name,
	course_id
) values (
	'HTML - CSS',
	1
) , (
	'REACT',
	2
);